[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.regex]
target = "functions/UI_definitions.lua"
pattern = '''(?<indent>[\t ]*)\{n=G\.UIT\.C, config=\{align = "cm", padding = 0\.1\}, nodes=\{t\.nodes\[1\]\}\r?\n[\t ]*\}'''
position = "at"
payload = '''
{n=G.UIT.C, config={align = "cm", padding = 0.1}, nodes={t.nodes[1]}},
{n=G.UIT.C, config={align = "cm", padding = 0.1}, nodes={
        G.GAME.modifiers.impy_leaderboard
            and BALALADLE.UI.get_leaderboard()
            or nil,
    }
}
'''
line_prepend = "$indent"
times = 1

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "local Jimbo = nil"
position = "after"
payload = '''
if G.GAME.modifiers.impy_leaderboard then
    local function recalculate_leaderboard_ui(delay)
        G.E_MANAGER:add_event(Event({
            trigger = "after",
            delay = delay,
            blocking = false,
            func = function()
                if G.OVERLAY_MENU then
                    G.OVERLAY_MENU:recalculate()
                end

                return true
            end
        }))
    end

    for i = 1, 15 do
        recalculate_leaderboard_ui(i * 0.02)
    end
end
'''
match_indent = true